name: login
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.0
  http: any
  rflutter_alert: ^1.0.2
  google_maps_flutter: ^0.5.7
  location: ^1.4.1
  intl: any
  fluttertoast: ^2.1.4
dev_dependencies:
  flutter_test:
    sdk: flutter

  android_intent: "^0.2.1"

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/alucard.jpg
  fonts:
      - family: Nunito
        fonts:
          - asset: assets/Nunito.ttf